---
# Link node_modules

- name: link {{ library_name }}
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    - src: "{{ library_deploy_dest }}"
      dest: "{{ library_deploy_current }}"